import type { OkrWindowData } from "@/lib/okr/reference";

export const okrWindowFixture: OkrWindowData = {
  employeeName: "Saif Ivna Alam",
  quarterLabel: "2026-Q3",
  allQuarters: false,
  total: 3,
  items: [
    {
      id: "key_result:company-1",
      kind: "key_result",
      level: "company",
      quarter: "2026-Q3",
      quarterLabel: "Q3 2026",
      title: "Build Performance Platform Phase 1",
      shortTitle: "Build Performance Platform Phase 1",
      description: "Q3 Build, Q4 Testing, Q1 2027 Launch",
      objectiveTitle: "People Foundation — Build leadership and structure that scales",
      ownerLabel: "S.M. Fahim",
      status: "on_track",
      statusLabel: "On Track",
      roles: ["responsible"],
      unit: "%",
      currentValue: 20,
      targetValue: 100,
      progressPercent: 20,
      lastCheckIn: {
        weekNumber: 9,
        statusLabel: "On Track",
        note: "Weekly update",
        submittedAt: "2026-08-21T09:18:42.548Z",
        authorName: "S.M. Fahim",
      },
      raci: {
        accountable: [{ employeeId: 201, email: "", label: "S.M. Fahim" }],
        responsible: [{ employeeId: 871, email: "", label: "Saif Ivna Alam" }],
        consulted: [],
        informed: [],
      },
      milestones: [],
    },
    {
      id: "key_result:dept-1",
      kind: "key_result",
      level: "department",
      quarter: "2026-Q3",
      quarterLabel: "Q3 2026",
      title: "Improve customer outcomes across Engineering",
      shortTitle: "Improve customer outcomes across Engineering",
      description: "",
      objectiveTitle: "Strengthen People Capability",
      ownerLabel: "Api Singha",
      status: "on_track",
      statusLabel: "On Track",
      roles: ["responsible"],
      unit: "%",
      currentValue: 50,
      targetValue: 100,
      progressPercent: 50,
      lastCheckIn: null,
      raci: {
        accountable: [{ employeeId: 100, email: "", label: "Api Singha" }],
        responsible: [
          { employeeId: null, email: "", label: "Engineering squad leads" },
        ],
        consulted: [],
        informed: [],
      },
      milestones: [],
    },
    {
      id: "key_result:wing-1",
      kind: "key_result",
      level: "wing",
      quarter: "2026-Q3",
      quarterLabel: "Q3 2026",
      title: "Keep dependencies and delivery risks visible",
      shortTitle: "Keep dependencies and delivery risks visible",
      description: "",
      objectiveTitle: "Deliver Platform priorities predictably",
      ownerLabel: "Platform wing",
      status: "on_track",
      statusLabel: "On Track",
      roles: ["responsible"],
      unit: "%",
      currentValue: 40,
      targetValue: 100,
      progressPercent: 40,
      lastCheckIn: null,
      raci: {
        accountable: [{ employeeId: null, email: "", label: "Platform owner" }],
        responsible: [{ employeeId: null, email: "", label: "Platform delivery" }],
        consulted: [{ employeeId: null, email: "", label: "PMO" }],
        informed: [
          { employeeId: null, email: "", label: "Engineering department" },
        ],
      },
      milestones: [],
    },
  ],
};
