import type { OkrWindowData } from "@/lib/okr/reference";

export const okrWindowFixture: OkrWindowData = {
  employeeName: "Saif Ivna Alam",
  quarterLabel: "2026-Q3",
  allQuarters: false,
  total: 3,
  items: [
    {
      id: "key_result:5e569c65-60a0-4216-948b-a3010a023655",
      keyResultId: "5e569c65-60a0-4216-948b-a3010a023655",
      objectiveId: "c2a30c75-0e03-4e3c-bbcd-49fab62b6c1a",
      kind: "key_result",
      level: "company",
      quarter: "2026-Q3",
      quarterLabel: "Q3 2026",
      title: "Build Performance Platform Phase 1",
      shortTitle: "Build Performance Platform Phase 1",
      description: "Q3 Build, Q4 Testing, Q1 2027 Launch",
      objectiveTitle: "People Foundation - Build leadership and structure that scales",
      ownerLabel: "S.M. Fahim",
      status: "on_track",
      statusLabel: "On Track",
      roles: ["responsible"],
      unit: "%",
      trackType: "milestone",
      direction: "increase",
      startValue: 0,
      currentValue: 20,
      targetValue: 100,
      progressPercent: 20,
      lastCheckIn: {
        weekNumber: 9,
        statusLabel: "On Track",
        note: "Weekly update",
        submittedAt: "2026-08-21T09:18:42.548Z",
        authorName: "S.M. Fahim",
      },
      raci: {
        accountable: [{ employeeId: 201, email: "", label: "S.M. Fahim" }],
        responsible: [{ employeeId: 871, email: "", label: "Saif Ivna Alam" }],
        consulted: [],
        informed: [],
      },
      milestones: [],
      linkedKrs: [
        {
          keyResultId: "linked-kr-1",
          objectiveId: "obj-linked-1",
          title: "Critical Hiring",
          objectiveTitle: "Build a High-Performance Organisation",
          ownerLabel: "bhaskar",
          weight: 100,
          tierLabel: "T3",
          level: "department",
        },
        {
          keyResultId: "linked-kr-2",
          objectiveId: "obj-linked-2",
          title: "Maintain 90% Workforce Capacity",
          objectiveTitle: "Workforce & Capability Building",
          ownerLabel: "Ong Choon Khai",
          weight: 100,
          tierLabel: "T4",
          level: "wing",
        },
      ],
      tierLabel: "T1",
    },
    {
      id: "key_result:dept-1",
      keyResultId: "dept-1",
      objectiveId: "obj-dept-1",
      kind: "key_result",
      level: "department",
      quarter: "2026-Q3",
      quarterLabel: "Q3 2026",
      title: "Improve customer outcomes across Engineering",
      shortTitle: "Improve customer outcomes across Engineering",
      description: "",
      objectiveTitle: "Strengthen People Capability",
      ownerLabel: "Api Singha",
      status: "on_track",
      statusLabel: "On Track",
      roles: ["responsible"],
      unit: "%",
      trackType: "percent",
      direction: "increase",
      startValue: null,
      currentValue: 50,
      targetValue: 100,
      progressPercent: 50,
      lastCheckIn: null,
      raci: {
        accountable: [{ employeeId: 100, email: "", label: "Api Singha" }],
        responsible: [
          { employeeId: null, email: "", label: "Engineering squad leads" },
        ],
        consulted: [],
        informed: [],
      },
      milestones: [],
      linkedKrs: [],
      tierLabel: "T2",
    },
    {
      id: "key_result:wing-1",
      keyResultId: "wing-1",
      objectiveId: "obj-wing-1",
      kind: "key_result",
      level: "wing",
      quarter: "2026-Q3",
      quarterLabel: "Q3 2026",
      title: "Keep dependencies and delivery risks visible",
      shortTitle: "Keep dependencies and delivery risks visible",
      description: "",
      objectiveTitle: "Deliver Platform priorities predictably",
      ownerLabel: "Platform wing",
      status: "on_track",
      statusLabel: "On Track",
      roles: ["responsible"],
      unit: "",
      trackType: "milestone",
      direction: "",
      startValue: null,
      currentValue: null,
      targetValue: null,
      progressPercent: 40,
      lastCheckIn: null,
      raci: {
        accountable: [{ employeeId: null, email: "", label: "Platform owner" }],
        responsible: [{ employeeId: null, email: "", label: "Platform delivery" }],
        consulted: [{ employeeId: null, email: "", label: "PMO" }],
        informed: [
          { employeeId: null, email: "", label: "Engineering department" },
        ],
      },
      milestones: [
        { id: "wing-ms-1", title: "Risk register live", status: "completed", weight: 50 },
        { id: "wing-ms-2", title: "Weekly risk review", status: "in_progress", weight: 50 },
      ],
      linkedKrs: [],
      tierLabel: "T4",
    },
  ],
};
