import type { Skill } from './types'

export const SEED_SKILLS: Skill[] = [
  {
    id: 'skill-account-planning',
    name: 'Account Planning',
    function: 'Sales',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-accuracy',
    name: 'Accuracy',
    function: '',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-financial-accuracy',
    name: 'Accuracy in Financial Processing',
    function: 'Finance',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-acquisition-negotiation',
    name: 'Acquisition and Negotiation',
    function: '',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-admin-support',
    name: 'Administrative Support',
    function: 'HR',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-ai-fluency',
    name: 'AI Fluency',
    function: 'Strategic Execution',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-analytical-methods',
    name: 'Analytical and Statistical Methods',
    function: 'Product',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-analytical-thinking',
    name: 'Analytical Thinking',
    function: 'Trading & Risk',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-stakeholder-comms',
    name: 'Stakeholder Communication',
    function: '',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-delivery-ownership',
    name: 'Delivery Ownership',
    function: 'Engineering',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-people-leadership',
    name: 'People Leadership',
    function: '',
    role: 'Manager',
    status: 'approved',
  },
  {
    id: 'skill-coaching',
    name: 'Coaching and Feedback',
    function: '',
    role: 'Manager',
    status: 'approved',
  },
  {
    id: 'skill-data-storytelling',
    name: 'Analytical Insight and Context Building',
    function: 'Product',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-risk-judgement',
    name: 'Risk Judgement',
    function: 'Trading & Risk',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-process-design',
    name: 'Process Design',
    function: 'Operations',
    role: '',
    status: 'approved',
  },
  {
    id: 'skill-written-comms',
    name: 'Written Communication',
    function: '',
    role: '',
    status: 'approved',
  },
]
