import { NOTIFICATION_CATALOGUE, NOTIFICATION_EVENTS } from './catalogue'
import type { NotificationRule, NotificationRuleCategory } from './ruleTypes'
import type { NotificationChannel } from './types'

type RuleMeta = {
  name: string
  category: NotificationRuleCategory
  audienceKey: string
  audienceLabel: string
  whenLabel: string
  timingKind: NotificationRule['timingKind']
  sortOrder: number
  titleTemplate?: string
  bodyTemplate?: string
  channels?: NotificationChannel[]
}

const META: Record<string, RuleMeta> = {
  [NOTIFICATION_EVENTS.GOAL_WINDOW_OPENED]: {
    name: 'Goal setting opens',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Each employee in the cycle',
    whenLabel: 'When the goal window opens',
    timingKind: 'immediate',
    sortOrder: 10,
  },
  [NOTIFICATION_EVENTS.GOAL_DAY_7_REMINDER]: {
    name: 'Goals still pending (day 7)',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees who have not submitted',
    whenLabel: '7 days into the goal window',
    timingKind: 'reminder',
    sortOrder: 20,
  },
  [NOTIFICATION_EVENTS.GOAL_DAY_14_REMINDER]: {
    name: 'Goal deadline approaching (day 14)',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees who have not submitted',
    whenLabel: '14 days into the goal window',
    timingKind: 'reminder',
    sortOrder: 30,
  },
  [NOTIFICATION_EVENTS.GOAL_DAY_25_REMINDER]: {
    name: '5 days left to submit goals',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees who have not submitted',
    whenLabel: '25 days into the goal window',
    timingKind: 'reminder',
    sortOrder: 40,
  },
  [NOTIFICATION_EVENTS.GOAL_DEADLINE_PASSED_EXCEPTIONS]: {
    name: 'Goal deadline passed (late still open)',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees who can still submit late',
    whenLabel: 'When the goal deadline passes with late exceptions',
    timingKind: 'immediate',
    sortOrder: 50,
  },
  [NOTIFICATION_EVENTS.GOAL_DEADLINE_CLOSED]: {
    name: 'Goal submission closed',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees in the cycle',
    whenLabel: 'When goal submission closes',
    timingKind: 'immediate',
    sortOrder: 60,
  },
  [NOTIFICATION_EVENTS.GOAL_MANUAL_REMINDER]: {
    name: 'Manual reminder from manager',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee the manager reminds',
    whenLabel: 'When a manager sends a reminder',
    timingKind: 'immediate',
    sortOrder: 70,
  },
  [NOTIFICATION_EVENTS.GOAL_TEAM_PENDING_SUMMARY]: {
    name: 'Team still needs to submit',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'Managers with pending reports',
    whenLabel: 'When a manager has people who still need to submit',
    timingKind: 'reminder',
    sortOrder: 80,
  },
  [NOTIFICATION_EVENTS.GOAL_SUBMITTED]: {
    name: 'Goals need approval',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When someone submits goals',
    timingKind: 'immediate',
    sortOrder: 90,
  },
  [NOTIFICATION_EVENTS.GOAL_RESUBMITTED]: {
    name: 'Goals resubmitted',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When someone resubmits goals',
    timingKind: 'immediate',
    sortOrder: 100,
  },
  [NOTIFICATION_EVENTS.GOAL_MANAGER_EDITED]: {
    name: 'Manager edited goals',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When a manager edits their goals',
    timingKind: 'immediate',
    sortOrder: 110,
  },
  [NOTIFICATION_EVENTS.GOAL_SENT_BACK]: {
    name: 'Goals sent back',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When goals are sent back for changes',
    timingKind: 'immediate',
    sortOrder: 120,
  },
  [NOTIFICATION_EVENTS.GOAL_APPROVED]: {
    name: 'Goals approved by manager',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When a manager approves goals',
    timingKind: 'immediate',
    sortOrder: 130,
  },
  [NOTIFICATION_EVENTS.GOAL_LATE_SUBMITTED]: {
    name: 'Late goals need approval',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When someone submits goals after the deadline',
    timingKind: 'immediate',
    sortOrder: 140,
  },
  [NOTIFICATION_EVENTS.GOAL_FINAL_APPROVAL_REQUESTED]: {
    name: 'Final approval needed',
    category: 'goals',
    audienceKey: 'skip_level',
    audienceLabel: 'Skip-level / final approver',
    whenLabel: 'When manager approval is done and final approval is needed',
    timingKind: 'immediate',
    sortOrder: 150,
  },
  [NOTIFICATION_EVENTS.GOAL_PENDING_FINAL_APPROVAL]: {
    name: 'Waiting on final approval',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When goals are waiting on final approval',
    timingKind: 'immediate',
    sortOrder: 160,
  },
  [NOTIFICATION_EVENTS.GOAL_FINAL_APPROVED]: {
    name: 'Goals fully approved',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When final approval is granted',
    timingKind: 'immediate',
    sortOrder: 170,
  },
  [NOTIFICATION_EVENTS.GOAL_FINAL_APPROVED_MANAGER]: {
    name: 'Report’s goals fully approved',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When a report’s goals get final approval',
    timingKind: 'immediate',
    sortOrder: 180,
  },
  [NOTIFICATION_EVENTS.GOAL_FINAL_SENT_BACK]: {
    name: 'Final approver requested changes',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When final approval sends goals back',
    timingKind: 'immediate',
    sortOrder: 190,
  },
  [NOTIFICATION_EVENTS.GOAL_FINAL_SENT_BACK_MANAGER]: {
    name: 'Report’s goals sent back by final approver',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When final approval sends a report’s goals back',
    timingKind: 'immediate',
    sortOrder: 200,
  },
  [NOTIFICATION_EVENTS.GOAL_CHANGES_REQUIRE_APPROVAL]: {
    name: 'Goal changes need approval',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When approved goals are changed and need re-approval',
    timingKind: 'immediate',
    sortOrder: 210,
  },
  [NOTIFICATION_EVENTS.GOAL_RESULTS_REMINDER]: {
    name: 'Update goal results',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees with open results',
    whenLabel: 'When results updates are due',
    timingKind: 'reminder',
    sortOrder: 220,
  },
  [NOTIFICATION_EVENTS.GOAL_STALE_TEAM_SUMMARY]: {
    name: 'Stale progress on the team',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'Managers with stale reports',
    whenLabel: 'When reports have not updated progress recently',
    timingKind: 'reminder',
    sortOrder: 230,
  },
  [NOTIFICATION_EVENTS.GOAL_PROGRESS_ADJUSTED]: {
    name: 'Goal progress updated by manager',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When a manager adjusts progress',
    timingKind: 'immediate',
    sortOrder: 240,
  },
  [NOTIFICATION_EVENTS.GOAL_CHECK_IN_COMPLETED]: {
    name: 'Check-in completed',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When a performance check-in is completed',
    timingKind: 'immediate',
    sortOrder: 250,
  },
  [NOTIFICATION_EVENTS.GOAL_CASCADED]: {
    name: 'Goal cascaded to you',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The person receiving the cascade',
    whenLabel: 'When a manager cascades a goal',
    timingKind: 'immediate',
    sortOrder: 260,
  },
  [NOTIFICATION_EVENTS.GOAL_COMMENT_MENTIONED]: {
    name: 'Mentioned in a goal comment',
    category: 'goals',
    audienceKey: 'involved',
    audienceLabel: 'The mentioned person',
    whenLabel: 'When someone is @mentioned in a goal comment',
    timingKind: 'immediate',
    sortOrder: 270,
  },
  [NOTIFICATION_EVENTS.REVIEW_SELF_OPENED]: {
    name: 'Self-review opens',
    category: 'reviews',
    audienceKey: 'employee',
    audienceLabel: 'Each employee in the cycle',
    whenLabel: 'When self-review opens',
    timingKind: 'immediate',
    sortOrder: 300,
  },
  [NOTIFICATION_EVENTS.REVIEW_ASSIGNED]: {
    name: 'Review assigned to manager',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The reviewer',
    whenLabel: 'When a manager review is assigned',
    timingKind: 'immediate',
    sortOrder: 310,
  },
  [NOTIFICATION_EVENTS.REVIEW_DUE_SOON]: {
    name: 'Review due soon',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The reviewer',
    whenLabel: 'A few days before a review is due',
    timingKind: 'reminder',
    sortOrder: 320,
  },
  [NOTIFICATION_EVENTS.REVIEW_OVERDUE]: {
    name: 'Review overdue',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The reviewer',
    whenLabel: 'When a review is past due',
    timingKind: 'reminder',
    sortOrder: 330,
  },
  [NOTIFICATION_EVENTS.REVIEW_SELF_SUBMITTED]: {
    name: 'Self-review submitted',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When someone finishes self-review',
    timingKind: 'immediate',
    sortOrder: 340,
  },
  [NOTIFICATION_EVENTS.REVIEW_MANAGER_OPENED]: {
    name: 'Manager reviews ready',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'Managers with reviews to write',
    whenLabel: 'When manager review opens',
    timingKind: 'immediate',
    sortOrder: 350,
  },
  [NOTIFICATION_EVENTS.REVIEW_READY_FOR_CALIBRATION]: {
    name: 'Ready for calibration',
    category: 'reviews',
    audienceKey: 'administrators',
    audienceLabel: 'Calibrators / HR',
    whenLabel: 'When manager reviews are complete and ready to calibrate',
    timingKind: 'immediate',
    sortOrder: 360,
  },
  [NOTIFICATION_EVENTS.REVIEW_CALIBRATION_OPENED]: {
    name: 'Calibration opens',
    category: 'reviews',
    audienceKey: 'administrators',
    audienceLabel: 'Calibrators',
    whenLabel: 'When calibration opens',
    timingKind: 'immediate',
    sortOrder: 370,
  },
  [NOTIFICATION_EVENTS.REVIEW_CALIBRATION_DUE_SOON]: {
    name: 'Calibration due soon',
    category: 'reviews',
    audienceKey: 'administrators',
    audienceLabel: 'Calibrators',
    whenLabel: 'A few days before calibration closes',
    timingKind: 'reminder',
    sortOrder: 380,
  },
  [NOTIFICATION_EVENTS.REVIEW_READY_TO_PUBLISH]: {
    name: 'Ready to publish results',
    category: 'reviews',
    audienceKey: 'administrators',
    audienceLabel: 'Cycle admins / HR',
    whenLabel: 'When calibration is complete and results can publish',
    timingKind: 'immediate',
    sortOrder: 390,
  },
  [NOTIFICATION_EVENTS.REVIEW_RESULTS_FOR_MANAGERS]: {
    name: 'Results available to managers',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'Managers',
    whenLabel: 'When results are released to managers',
    timingKind: 'immediate',
    sortOrder: 400,
  },
  [NOTIFICATION_EVENTS.REVIEW_RESULTS_PUBLISHED]: {
    name: 'Results published to employee',
    category: 'reviews',
    audienceKey: 'employee',
    audienceLabel: 'Each employee',
    whenLabel: 'When results are published',
    timingKind: 'immediate',
    sortOrder: 410,
  },
  [NOTIFICATION_EVENTS.REVIEW_RESULT_CORRECTED]: {
    name: 'Result corrected',
    category: 'reviews',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When an administrator corrects a result',
    timingKind: 'immediate',
    sortOrder: 420,
  },
  [NOTIFICATION_EVENTS.REVIEW_DEADLINE_UPDATED]: {
    name: 'Review deadline updated',
    category: 'reviews',
    audienceKey: 'involved',
    audienceLabel: 'People affected by the deadline',
    whenLabel: 'When a cycle deadline changes',
    timingKind: 'immediate',
    sortOrder: 430,
  },
  'review_packet.calibrated': {
    name: 'Calibration grade changed',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When calibration changes someone’s grade',
    timingKind: 'immediate',
    sortOrder: 440,
    titleTemplate: 'Calibration grade changed',
    bodyTemplate: '{{employee}}’s grade is now {{grade}}',
    channels: ['in_app'],
  },
  [NOTIFICATION_EVENTS.ORG_MANAGER_CHANGED_EMPLOYEE]: {
    name: 'Your manager changed',
    category: 'organisation',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When someone’s manager changes',
    timingKind: 'immediate',
    sortOrder: 500,
  },
  [NOTIFICATION_EVENTS.ORG_MANAGER_CHANGED_MANAGER]: {
    name: 'New report assigned',
    category: 'organisation',
    audienceKey: 'manager',
    audienceLabel: 'The new manager',
    whenLabel: 'When someone starts reporting to them',
    timingKind: 'immediate',
    sortOrder: 510,
  },
  [NOTIFICATION_EVENTS.ACCESS_GRANTED]: {
    name: 'Admin access granted',
    category: 'access',
    audienceKey: 'employee',
    audienceLabel: 'The person who received access',
    whenLabel: 'When admin access is granted',
    timingKind: 'immediate',
    sortOrder: 600,
  },
  [NOTIFICATION_EVENTS.ACCESS_REMOVED]: {
    name: 'Admin access removed',
    category: 'access',
    audienceKey: 'employee',
    audienceLabel: 'The person who lost access',
    whenLabel: 'When admin access is removed',
    timingKind: 'immediate',
    sortOrder: 610,
  },
}

function buildDefault(eventKey: string, meta: RuleMeta): NotificationRule {
  const catalogue = NOTIFICATION_CATALOGUE.get(eventKey)
  return {
    eventKey,
    name: meta.name,
    category: meta.category,
    audienceKey: meta.audienceKey,
    audienceLabel: meta.audienceLabel,
    whenLabel: meta.whenLabel,
    timingKind: meta.timingKind,
    enabled: true,
    channels: (meta.channels ??
      catalogue?.channels ?? ['in_app']) as NotificationChannel[],
    titleTemplate: meta.titleTemplate ?? catalogue?.title ?? meta.name,
    bodyTemplate: meta.bodyTemplate ?? catalogue?.body ?? '',
    sortOrder: meta.sortOrder,
  }
}

export const NOTIFICATION_RULE_DEFAULTS: NotificationRule[] = Object.entries(
  META,
).map(([eventKey, meta]) => buildDefault(eventKey, meta))

export const NOTIFICATION_RULE_DEFAULTS_BY_KEY = new Map(
  NOTIFICATION_RULE_DEFAULTS.map((rule) => [rule.eventKey, rule]),
)

export function getDefaultNotificationRule(
  eventKey: string,
): NotificationRule | null {
  return NOTIFICATION_RULE_DEFAULTS_BY_KEY.get(eventKey) ?? null
}
