/**
 * Default notification rules — mirrors the client catalogue with admin-facing
 * labels. ensureSeeded() inserts any missing event_key from this list.
 */

const inApp = ['in_app', 'browser']
const inAppAndEmail = ['in_app', 'email', 'browser']

function rule(definition) {
  return definition
}

/** @type {ReadonlyArray<ReturnType<typeof rule>>} */
export const NOTIFICATION_RULE_DEFAULTS = [
  rule({
    eventKey: 'goal.window_opened',
    name: 'Goal setting opens',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Each employee in the cycle',
    whenLabel: 'When the goal window opens',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Goal setting is open',
    bodyTemplate: '{{cycle}} · due {{deadline}}',
    sortOrder: 10,
  }),
  rule({
    eventKey: 'goal.reminder.day_7',
    name: 'Goals still pending (day 7)',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees who have not submitted',
    whenLabel: '7 days into the goal window',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Goals still pending',
    bodyTemplate: '{{cycle}} · due {{deadline}}',
    sortOrder: 20,
  }),
  rule({
    eventKey: 'goal.reminder.day_14',
    name: 'Goal deadline approaching (day 14)',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees who have not submitted',
    whenLabel: '14 days into the goal window',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Goal deadline approaching',
    bodyTemplate: '{{days}} days left · {{cycle}}',
    sortOrder: 30,
  }),
  rule({
    eventKey: 'goal.reminder.day_25',
    name: '5 days left to submit goals',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees who have not submitted',
    whenLabel: '25 days into the goal window',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '5 days left to submit goals',
    bodyTemplate: '{{cycle}} · due {{deadline}}',
    sortOrder: 40,
  }),
  rule({
    eventKey: 'goal.deadline.exceptions',
    name: 'Goal deadline passed (late still open)',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees who can still submit late',
    whenLabel: 'When the goal deadline passes with late exceptions',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Goal deadline has passed',
    bodyTemplate: 'Late {{cycle}} submissions still accepted',
    sortOrder: 50,
  }),
  rule({
    eventKey: 'goal.deadline.closed',
    name: 'Goal submission closed',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees in the cycle',
    whenLabel: 'When goal submission closes',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Goal submission is closed',
    bodyTemplate: '{{cycle}} · closed {{deadline}}',
    sortOrder: 60,
  }),
  rule({
    eventKey: 'goal.reminder.manual',
    name: 'Manual reminder from manager',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee the manager reminds',
    whenLabel: 'When a manager sends a reminder',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Reminder from {{manager}}',
    bodyTemplate: '{{message}}',
    sortOrder: 70,
  }),
  rule({
    eventKey: 'goal.team.pending_summary',
    name: 'Team still needs to submit',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'Managers with pending reports',
    whenLabel: 'When a manager has people who still need to submit',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{count}} people still need to submit',
    bodyTemplate: '{{cycle}} goals pending',
    sortOrder: 80,
  }),
  rule({
    eventKey: 'goal.submitted',
    name: 'Goals need approval',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When someone submits goals',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '{{employee}}’s goals need approval',
    bodyTemplate: '{{count}} goals · {{cycle}}',
    sortOrder: 90,
  }),
  rule({
    eventKey: 'goal.resubmitted',
    name: 'Goals resubmitted',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When someone resubmits goals',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '{{employee}} resubmitted goals',
    bodyTemplate: 'Updated {{cycle}} submission',
    sortOrder: 100,
  }),
  rule({
    eventKey: 'goal.manager_edited',
    name: 'Manager edited goals',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When a manager edits their goals',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Your goals were updated',
    bodyTemplate: '{{manager}} · {{cycle}}',
    sortOrder: 110,
  }),
  rule({
    eventKey: 'goal.sent_back',
    name: 'Goals sent back',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When goals are sent back for changes',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Goals sent back',
    bodyTemplate: '{{approver}}: “{{reason}}”',
    sortOrder: 120,
  }),
  rule({
    eventKey: 'goal.approved',
    name: 'Goals approved by manager',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When a manager approves goals',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: 'Your goals were approved',
    bodyTemplate: '{{manager}} · {{cycle}}',
    sortOrder: 130,
  }),
  rule({
    eventKey: 'goal.late_submitted',
    name: 'Late goals need approval',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When someone submits goals after the deadline',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Late goals need approval',
    bodyTemplate: '{{employee}} · {{cycle}}',
    sortOrder: 140,
  }),
  rule({
    eventKey: 'goal.final_approval_requested',
    name: 'Final approval needed',
    category: 'goals',
    audienceKey: 'skip_level',
    audienceLabel: 'Skip-level / final approver',
    whenLabel: 'When manager approval is done and final approval is needed',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Final approval needed for {{employee}}',
    bodyTemplate: '{{manager}} approved · your turn',
    sortOrder: 150,
  }),
  rule({
    eventKey: 'goal.pending_final_approval',
    name: 'Waiting on final approval',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When goals are waiting on final approval',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: 'Pending final approval',
    bodyTemplate: 'Waiting on {{skipLevelManager}}',
    sortOrder: 160,
  }),
  rule({
    eventKey: 'goal.final_approved',
    name: 'Goals fully approved',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When final approval is granted',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Goals fully approved',
    bodyTemplate: '{{skipLevelManager}} · {{cycle}}',
    sortOrder: 170,
  }),
  rule({
    eventKey: 'goal.final_approved.manager',
    name: 'Report’s goals fully approved',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When a report’s goals get final approval',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{employee}}’s goals fully approved',
    bodyTemplate: '{{skipLevelManager}} · {{cycle}}',
    sortOrder: 180,
  }),
  rule({
    eventKey: 'goal.final_sent_back',
    name: 'Final approver requested changes',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When final approval sends goals back',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Changes requested',
    bodyTemplate: '{{skipLevelManager}}: “{{reason}}”',
    sortOrder: 190,
  }),
  rule({
    eventKey: 'goal.final_sent_back.manager',
    name: 'Report’s goals sent back by final approver',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When final approval sends a report’s goals back',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{employee}}’s goals sent back',
    bodyTemplate: '{{skipLevelManager}} requested changes',
    sortOrder: 200,
  }),
  rule({
    eventKey: 'goal.changes_require_approval',
    name: 'Goal changes need approval',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When approved goals are changed and need re-approval',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Goal changes need approval',
    bodyTemplate: '{{employee}} · {{cycle}}',
    sortOrder: 210,
  }),
  rule({
    eventKey: 'goal.results_reminder',
    name: 'Update goal results (14 days before cycle end)',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'Employees with open results',
    whenLabel: '14 days before the cycle ends',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Update your goal results',
    bodyTemplate: '{{cycle}} closes {{deadline}}',
    sortOrder: 220,
  }),
  rule({
    eventKey: 'goal.team.stale_summary',
    name: 'Stale progress on the team (14 days)',
    category: 'goals',
    audienceKey: 'manager',
    audienceLabel: 'Managers with stale reports',
    whenLabel: 'When reports have no progress update for 14 days',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{count}} people have stale progress',
    bodyTemplate: 'No updates since {{thresholdDate}}',
    sortOrder: 230,
  }),
  rule({
    eventKey: 'goal.progress_adjusted',
    name: 'Goal progress updated by manager',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When a manager adjusts progress',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: 'Goal progress updated',
    bodyTemplate: '{{manager}} · {{count}} metrics',
    sortOrder: 240,
  }),
  rule({
    eventKey: 'goal.check_in_completed',
    name: 'Check-in completed',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When a performance check-in is completed',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: 'Performance review complete',
    bodyTemplate: '{{manager}} · {{cycle}}',
    sortOrder: 250,
  }),
  rule({
    eventKey: 'goal.cascaded',
    name: 'Goal cascaded to you',
    category: 'goals',
    audienceKey: 'employee',
    audienceLabel: 'The person receiving the cascade',
    whenLabel: 'When a manager cascades a goal',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{manager}} cascaded a goal',
    bodyTemplate: '“{{goal}}” · {{cycle}}',
    sortOrder: 260,
  }),
  rule({
    eventKey: 'goal.comment.mentioned',
    name: 'Mentioned in a goal comment',
    category: 'goals',
    audienceKey: 'involved',
    audienceLabel: 'The mentioned person',
    whenLabel: 'When someone is @mentioned in a goal comment',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '{{actor}} mentioned you',
    bodyTemplate: '“{{comment}}”',
    sortOrder: 270,
  }),

  rule({
    eventKey: 'review.self.opened',
    name: 'Self-review opens',
    category: 'reviews',
    audienceKey: 'employee',
    audienceLabel: 'Each employee in the cycle',
    whenLabel: 'When self-review opens',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Self-review is ready',
    bodyTemplate: '{{cycle}} · due {{deadline}}',
    sortOrder: 300,
  }),
  rule({
    eventKey: 'review.assigned',
    name: 'Review assigned to manager',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The reviewer',
    whenLabel: 'When a manager review is assigned',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Review requested for {{employee}}',
    bodyTemplate: '{{reviewType}} · due {{deadline}}',
    sortOrder: 310,
  }),
  rule({
    eventKey: 'review.due_soon',
    name: 'Review due in 3 days',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The reviewer',
    whenLabel: '3 days before a review is due',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '{{days}} days left on a review',
    bodyTemplate: '{{employee}} · due {{deadline}}',
    sortOrder: 320,
  }),
  rule({
    eventKey: 'review.overdue',
    name: 'Review overdue',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The reviewer',
    whenLabel: 'When a review is past due',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Review overdue for {{employee}}',
    bodyTemplate: '{{cycle}} review still open',
    sortOrder: 330,
  }),
  rule({
    eventKey: 'review.self.submitted',
    name: 'Self-review submitted',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When someone finishes self-review',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{employee}} finished self-review',
    bodyTemplate: 'Ready for your {{cycle}} review',
    sortOrder: 340,
  }),
  rule({
    eventKey: 'review.manager.opened',
    name: 'Manager reviews ready',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'Managers with reviews to write',
    whenLabel: 'When manager review opens',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '{{count}} reviews are ready',
    bodyTemplate: '{{cycle}} · due {{deadline}}',
    sortOrder: 350,
  }),
  rule({
    eventKey: 'review.ready_for_calibration',
    name: 'Ready for calibration',
    category: 'reviews',
    audienceKey: 'administrators',
    audienceLabel: 'Calibrators / HR',
    whenLabel: 'When manager reviews are complete and ready to calibrate',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{count}} reviews ready to calibrate',
    bodyTemplate: '{{scope}} manager reviews complete',
    sortOrder: 360,
  }),
  rule({
    eventKey: 'review.calibration.opened',
    name: 'Calibration opens',
    category: 'reviews',
    audienceKey: 'administrators',
    audienceLabel: 'Calibrators',
    whenLabel: 'When calibration opens',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Calibration open for {{scope}}',
    bodyTemplate: '{{count}} scorecards · due {{deadline}}',
    sortOrder: 370,
  }),
  rule({
    eventKey: 'review.calibration.due_soon',
    name: 'Calibration closes in 3 days',
    category: 'reviews',
    audienceKey: 'administrators',
    audienceLabel: 'Calibrators',
    whenLabel: '3 days before calibration closes',
    timingKind: 'reminder',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Calibration closes in {{days}} days',
    bodyTemplate: '{{count}} left in {{scope}}',
    sortOrder: 380,
  }),
  rule({
    eventKey: 'review.ready_to_publish',
    name: 'Ready to publish results',
    category: 'reviews',
    audienceKey: 'administrators',
    audienceLabel: 'Cycle admins / HR',
    whenLabel: 'When calibration is complete and results can publish',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{cycle}} ready to publish',
    bodyTemplate: 'Calibration complete',
    sortOrder: 390,
  }),
  rule({
    eventKey: 'review.results_for_managers',
    name: 'Results available to managers',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'Managers',
    whenLabel: 'When results are released to managers',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '{{cycle}} results available',
    bodyTemplate: 'Publishes to everyone {{date}}',
    sortOrder: 400,
  }),
  rule({
    eventKey: 'review.results_published',
    name: 'Results published to employee',
    category: 'reviews',
    audienceKey: 'employee',
    audienceLabel: 'Each employee',
    whenLabel: 'When results are published',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Your {{cycle}} results are ready',
    bodyTemplate: 'Scorecard and feedback available',
    sortOrder: 410,
  }),
  rule({
    eventKey: 'review.result_corrected',
    name: 'Result corrected',
    category: 'reviews',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When an administrator corrects a result',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '{{cycle}} result updated',
    bodyTemplate: 'Corrected by {{administrator}}',
    sortOrder: 420,
  }),
  rule({
    eventKey: 'review.deadline_updated',
    name: 'Review deadline updated',
    category: 'reviews',
    audienceKey: 'involved',
    audienceLabel: 'People affected by the deadline',
    whenLabel: 'When a cycle deadline changes',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: '{{cycle}} deadline updated',
    bodyTemplate: '{{stage}}: {{oldDate}} → {{newDate}}',
    sortOrder: 430,
  }),
  rule({
    eventKey: 'review_packet.calibrated',
    name: 'Calibration grade changed',
    category: 'reviews',
    audienceKey: 'manager',
    audienceLabel: 'The employee’s manager',
    whenLabel: 'When calibration changes someone’s grade',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: 'Calibration grade changed',
    bodyTemplate: '{{employee}}’s grade is now {{grade}}',
    sortOrder: 440,
  }),

  rule({
    eventKey: 'org.manager_changed.employee',
    name: 'Your manager changed',
    category: 'organisation',
    audienceKey: 'employee',
    audienceLabel: 'The employee',
    whenLabel: 'When someone’s manager changes',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Your manager changed',
    bodyTemplate: '{{newManager}} is now your manager',
    sortOrder: 500,
  }),
  rule({
    eventKey: 'org.manager_changed.manager',
    name: 'New report assigned',
    category: 'organisation',
    audienceKey: 'manager',
    audienceLabel: 'The new manager',
    whenLabel: 'When someone starts reporting to them',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inApp],
    titleTemplate: '{{employee}} now reports to you',
    bodyTemplate: 'Open goals and reviews follow them',
    sortOrder: 510,
  }),

  rule({
    eventKey: 'access.granted',
    name: 'Admin access granted',
    category: 'access',
    audienceKey: 'employee',
    audienceLabel: 'The person who received access',
    whenLabel: 'When admin access is granted',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Access granted',
    bodyTemplate: '{{accessProfile}} · by {{administrator}}',
    sortOrder: 600,
  }),
  rule({
    eventKey: 'access.removed',
    name: 'Admin access removed',
    category: 'access',
    audienceKey: 'employee',
    audienceLabel: 'The person who lost access',
    whenLabel: 'When admin access is removed',
    timingKind: 'immediate',
    enabled: true,
    channels: [...inAppAndEmail],
    titleTemplate: 'Access removed',
    bodyTemplate: '{{accessProfile}} · by {{administrator}}',
    sortOrder: 610,
  }),
]

export const NOTIFICATION_RULE_DEFAULTS_BY_KEY = new Map(
  NOTIFICATION_RULE_DEFAULTS.map((item) => [item.eventKey, item]),
)

export const ALLOWED_CHANNELS = new Set([
  'in_app',
  'email',
  'clickup',
  'browser',
])
